dependencies:
- python=3.9.0
- pip
- pip:
  - numpy==1.20.3
  - torch==1.10.0
  - pandas==2.0.0
  - scikit-learn==1.0.1
  - mlserver==1.0.1
  - mlserver-mlflow==1.0.1
  - mlflow==1.25.1
  - cloudpickle==2.0.0
  - protobuf==3.20.0
  - pydantic==1.10.12
  - matplotlib
